name: Install terraform CDK

on:
  push:
    paths:
      - ".github/workflows/cdkinit.yml"

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Terraform CDK install and Init
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Terraform cdk (NPM)
        run: |
          sudo npm install -g cdktf-cli
      - name: Install pip and virtualenv
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          python -m pip install --upgrade virtualenv
      - name: CDK init
        run: |
          mkdir cdk-qhub-example
          cd cdk-qhub-example
          cdktf init --template="python-pip" --local --project-name='cdk-qhub-example' --project-description='A simple test for Qhub integration.'

      - name: Push Changes
        run: |
          git config user.email "vcerutti@quansight.com"
          git config user.name "github action"
          git add .
          # only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin "main")
        env:
          COMMIT_MSG: |
            automated commit: '${{ github.sha }}'
